build:
  stage: build
  script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build .
  artifacts:
    paths:
    - build/

test:
  stage: test
  script:
    - cd build
    - src/test_c
    - src/test_cc
    - src/test_f90

