test:cached_linux_release:
  stage: test
  tags: 
    - linux
  script:
    - ls .
    - mkdir -p build/release && cd build/release
    - cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=$PWD/INSTALL ../..
    - cmake --build .
    - ctest -j4
  artifacts:
    paths:
      - build/release/CMakeCache.txt
    expire_in: 1 week
  cache:
    key: "$CI_JOB_STAGE/$CI_COMMIT_REF_NAME"
    paths:
      - build/release
  except:
    - master

test:linux_debug:
  stage: test
  tags: 
    - linux
  script:
    - ls .
    - mkdir -p build/debug && cd build/debug
    - cmake -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_INSTALL_PREFIX=$PWD/INSTALL ../..
    - cmake --build .
    - ctest -j4
  artifacts:
    paths:
      - build/debug/CMakeCache.txt
    expire_in: 1 week
