sudo: required

dist: trusty

language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

before_install:
    - echo TRAVIS_OS_NAME=$TRAVIS_OS_NAME
    - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          sudo apt-get update -qq
          sudo apt-get install gfortran
          sudo apt-get install cmake
      else
          brew update &>/dev/null
          brew install gcc@4.8
          brew install cmake
      fi
    - cmake --version
    - gcc --version
    - g++ --version
    - gfortran --version

script:
    - mkdir build && cd build
    - cmake ..
    - make -j2
    - ctest -j2

