sudo: required

language: cpp

os:
    - linux

compiler:
    - gcc

before_install:
    - sudo apt-get install gfortran

script:
    - mkdir build && cd build
    - cmake ..
    - make -j2
    - ctest -j2

