sudo: required

dist: trusty

language: cpp

os:
    - linux

compiler:
    - gcc

before_install:
    - sudo apt-get install gfortran

script:
    - mkdir build && cd build
    - cmake ..
    - ctest --build .
    - ctest

