sudo: required

language: cpp

os:
    - linux

compiler:
    - gcc

before_install:
    - wget -q -O - https://www.mongodb.org/static/pgp/server-3.2.pub | sudo apt-key add -
    - sudo apt-get update -qq
    - sudo apt-get install gfortran
    - sudo apt-get install cmake
    - cmake --version
    - gcc --version
    - g++ --version
    - gfortran --version

script:
    - mkdir build && cd build
    - cmake ..
    - make -j2
    - ctest -j2

